---
title: Generator
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-midnight
gem 'jekyll-sitemap'
url: https://coinsgenerator.ballquant.io
plugins:
- jekyll-sitemap
